title: "Bryce's Dev Blog"
description: "SGD305 Development Log â€“ We have fun here."
author: Bryce Marrett
remote_theme: "mmistakes/minimal-mistakes@4.24.0-github-pages"
plugins:
  - jekyll-remote-theme
